### ISSUE TITLE
Error when install SDK on Ubuntu 18.04

### ISSUE THREAD

**Issue by artiya4u** [icon-project/icon_sdk_for_python#4]
I tried to install SDK on Ubuntu 18.04 with Python3.6 and got the error below.
```
    configure: creating ./config.status
    config.status: error: cannot find input file: `Makefile.in'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-avlcl2b2/secp256k1/setup.py", line 295, in <module>
        "Topic :: Security :: Cryptography"
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-avlcl2b2/secp256k1/setup.py", line 214, in run
        cwd=build_temp,
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-avlcl2b2/secp256k1/libsecp256k1/configure', '--disable-shared', '--enable-static', '--disable-dependency-tracking', '--with-pic', '--enable-module-recovery', '--prefix', '/tmp/pip-build-avlcl2b2/secp256k1/build/temp.linux-x86_64-3.6', '--without-bignum']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-avlcl2b2/secp256k1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i7c3upmu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-avlcl2b2/secp256k1/
```

**Comment by JinhoYoo-icon-project** [comment]
Thank you for your report! In our research, secp256k-1 package changed little but. 

For Ubuntu 18.x series, please install packages like following. ;-). We'll update the document in next release.

```
apt-get clean && \
    apt-get update && \
    apt-get install -y software-properties-common \
        python3-minimal  \
        python3-pip  \
        git \
        libsecp256k1-dev \
        build-essential \
        automake \
        pkg-config \
        libtool \
        libffi-dev \
        libgmp-dev \
        libssl-dev \
        curl \
        wget \
        locales && \
    apt-get clean && apt-get autoremove -y && \
    rm -rf /var/cache/apk/*
```

**Comment by artiya4u** [comment]
It's work! Thank you

**Comment by JinhoYoo-icon-project** [comment]
I'll close this issue.
